# Generated by Django 3.2.8 on 2021-12-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvodac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra_proizvodaca', models.CharField(max_length=10)),
                ('naziv_proizvodaca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vozilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra_vozila', models.CharField(max_length=10)),
                ('vrsta_vozila', models.CharField(max_length=30)),
                ('model_vozila', models.CharField(max_length=30)),
                ('godina_proizvodnje', models.CharField(max_length=10)),
                ('kilometraza', models.CharField(max_length=25)),
                ('boja', models.CharField(max_length=20)),
                ('cijena', models.CharField(max_length=25)),
                ('naziv_proizvodaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.proizvodac')),
            ],
        ),
    ]
