# Generated by Django 3.2.8 on 2021-12-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('uloga', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4096)),
                ('vrijeme', models.DateTimeField()),
                ('procitano', models.BooleanField(default=False)),
                ('posiljatelj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiljatelj', to='main.korisnik')),
                ('primatelj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primatelj', to='main.korisnik')),
            ],
        ),
    ]
