# Generated by Django 3.2.10 on 2022-02-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_korisnik_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vozilo',
            name='cijena',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vozilo',
            name='kilometraza',
            field=models.IntegerField(),
        ),
    ]
