# Generated by Django 3.2.10 on 2022-02-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220204_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vozilo',
            name='godina_proizvodnje',
            field=models.IntegerField(),
        ),
    ]
